#pragma once

#include <string>

std::string intro = "Despiertas muy cansado, tus ojos se sienten pesados y tu cabeza duele un poco. Miras a tu alrededor y parece que te quedaste dormido en medio de un bar, pero no lo reconoces. \n\nEn medio de tu confusión escuchas un tono de llamada. Sientes una vibración en tu bolsillo, es tu celular. Al observar la pantalla, notas que es un número desconocido, por lo que dudas si contestar o no.";

std::string a1 = "Te gana la curiosidad y decides contestar el celular. Escuchas una voz extraña que no logras reconocer. La persona te pide que te encuentres con ella en el callejón que se encuentra atrás del bar.";

std::string a2 = "Definitivamente es un pedido muy raro, pero te intriga demasiado. Entiendes que puede ser peligroso, pero aun así, no te importa. Decides aceptarlo y vas caminando al callejón. \n\nAl llegar ves una figura encapuchada muy misteriosa.Inicialmente, guardas una cierta distancia entre tú y ella, pero esta se termina poniendo justo en frente de ti y te susurra “En mi bolsillo derecho tengo un arma de fuego cargada y con un silenciador, en el otro tengo una tarjeta de débito con 45.6 billones de wones surcoreanos.” La figura te muestra su tarjeta, pone su arma en tu mano derecha y la posiciona para que le dispares en la cabeza.“Ahora mi arma está en tus manos, y si jalas el gatillo, la tarjeta también lo estará.”. \n\n¿Lo harás?";

std::string a3 = "La oferta es demasiado buena como para rechazarla. Por un breve instante ignoras todos los valores que se te inculcaron cuando eras niño, cierras los ojos y jalas el gatillo. Se escucha un disparo silenciado y mantienes los ojos cerrados por unos cuantos segundos. Con mucho miedo de qué ibas a ver, abres los ojos a la sorpresa de que la figura no estaba muerta, seguía de pie, en la misma posición.\n\nObservas la pistola y te percatas que saliendo de la boquilla hay un bandera que dice “BANG!”.La figura entonces dice : “Te ves bastante confundido.¿Realmente pensaste que te iba a dar una tarjeta con 45.6 billones de wones ? Wow, no puedo creerlo, pensé que habías cambiado, ahora veo que eres el mismo de siempre… Jesse”.La figura saca una pistola de verdad de su bolsillo trasero y te dispara justo en la frente.\n\nMueres instantáneamente.";

std::string b3 = "Por más tentadora que parece la oferta, no la puedes aceptar. Amablemente le dices a la persona que tendrás que rechazar su pedido y tiras la pistola. Por un momento hay un silencio profundo, pero notas algo raro, la persona está sonriendo. Es entonces cuando dice lo siguiente: “Vaya, vaya, vaya. Por fin lo lograste, eres un hombre completamente distinto” La figura se quita la capucha y da lugar al mayor plot twist de la historia, ¡ERA HANK DE BREAKING BAD TODO ESTE TIEMPO! Da una pausa breve y te dice “Por fin lo logré, Jesse, Walter White está tras las rejas y se pudrirá ahí hasta que llegue al infierno. Solo me quedaba determinar qué iba a hacer contigo, pero ya lo tengo claro, te dejaré en paz. Vamos, sigue con tu vida, Jesse. Disfruta tu libertad.”";

std::string b2 = "Cuelgas el teléfono inmediatamente. Nadie aceptaría un pedido como ese, ¿Qué, cree que estás loco? Miras la hora y vez que apenas son las 9 PM. Le preguntas al barman si pasan camiones que vayan por tu casa cerca del bar y te dice que pasan dos justo afuera, el 420 en la calle de la izquierda y el C-69 en la de la derecha. Le agradeces y pagas la cuenta. Sales del bar, pero no sabes si tomar un Uber/taxi o arriesgarte a ir en camión y perderte.";

std::string b1 = "Estás demasiado perdido como para contestarle a un desconocido. Decides no contestar y volver a casa lo más rápido posible. Miras la hora y vez que apenas son las 9 PM. Le preguntas al barman si pasan camiones que vayan por tu casa cerca del bar y te dice que pasan dos justo afuera, el 420 en la calle de la izquierda y el C-69 en la de la derecha. Le agradeces y pagas la cuenta. Sales del bar, pero no sabes si tomar un Uber/taxi o arriesgarte a ir en camión y perderte.";

std::string c2 = "Aunque sabes que no tienes mucho dinero después de gastar tanto dinero en el Free Fire, decides que vale la pena para asegurarte de llegar a casa, pero no sabes si irte en Uber o simplemente pedir un taxi a tu casa. Un taxi puede pasar muy rápido, pero no será tan seguro como un Uber.";

std::string e3 = "Decides mejor pedir un Uber y pagar el precio. Tarda un poco en llegar, pero cuando lo hace, sabes que va a ser un camino cómodo y libre de preocupaciones. Utilizas la aplicación para mandarle tu ubicación a tu familia y le pides al conductor que te despierte cuando lleguen.\n\nTe sientes muy cansado, por lo que no tardas mucho en quedarte dormido.Empiezas a soñar con que estás a punto cumplir tu propósito de vida, descubrir la fecha de nacimiento de tu coordinador de carrera, Mauricio Cabrera.Lamentablemente, antes de que puedas alcanzar la gloria, el conductor te despierta.\n\nAún norteadísimo, el conductor te dice “Serán $213, 086 pesos”.“No puede ser”, piensas, “es exactamente lo que me costó mi casa del INFONAVIT”.¿Qué harás en esta situación?";

std::string i4 = "Como no tenías suficiente dinero como para pagarle al Uber, decides utilizar tu casa como forma de pago. Como no tienes dónde pasar la noche, terminas trabajando tiempo extra como conductor de Uber para poder pagar la renta de un departamento pequeño.";

std::string j4 = "No tienes dinero para pagar el viaje de Uber, pero tampoco quieres dar tu casa como método de pago, por lo que decides salir corriendo lo más rápido posible. Al ver esto, el Uber se enoja, sale de su coche y saca una bazuca de la cajuela. Espera a que entres a tu casa y le dispara un misil. No solo terminas perdiendo tu casa, sino que pierdes la vida.";

std::string f3 = "Entiendes que puede ser menos seguro, pero no te importa, quieres llegar a tu casa lo más pronto posible. Casi inmediatamente pasa un taxi y te recoge.\n\nDurante el camino, el taxi no para de hablar de como “Los & ”# % $ de Uber no dejan de robarnos el trabajo”.Ya lleva horas y horas sin parar.Francamente, estás harto, y no sabes qué hacer al respecto.Sigues sin reconocer ninguna calle, parece que esta noche te alejaste mucho de tu hogar.\n\nYa te dejó de importar si llegas a casa o no, lo único que quieres es que se calle y deje de dar lata con su amor platónico no correspondido disfrazado de odio hacia los conductores de Uber.";

std::string k4 = "Crees que puede ser un poco grosero, pero no te importa, ya estás al borde. Al escucharte, el taxista gira su cuello 540° y te dice con una voz satánica “¡Sabía que eras un Ubermano, FUERA DE ESTE MUNDO!”. De la nada, sientes cómo tu cuerpo empieza a arder. Miras abajo y ves que literalmente estás en llamas. Antes de poder preguntarle al taxista sobre qué estaba pasando, parpadeas e inmediatamente eres transportado al inframundo, donde todos los tax-haters (de taxis, no de impuestos) terminan.";

std::string l4 = "Sientes que si le sigues al juego, va a calmarse y dejará de hablar. Después de decirle que también odias a los de Uber el taxista para su coche, y sin voltear atrás te dice “Sabía que eras un buen hijo de Dios, es hora de que vayas al paraíso”. Empiezas a escuchar voces angelicales y tu cuerpo empieza a elevarse, saliendo por el quema cocos. Una figura majestuosa se alcanza a ver a lo lejos del cielo. Se acerca a tí y te dice “Hijo mío, haz llegado muy lejos, es hora de que sepas la verdad… [REDACTED]”. Felicidades, lo lograste, por fin sabes la fecha de cumpleaños del coordinador de tu carrera, Mauricio Cabrera.";

std::string d2 = "Hoy amaneciste tacaño. No tienes idea de cuánto va a tardar en pasar uno de los dos camiones ni cuánto se vaya a demorar por las paradas, pero estás decidido a no pagar el viaje en uber/taxi. Ahora lo único que te falta decidir es cuál de los dos camiones esperar.";

std::string g3 = "Recuerdas las letras del gran Babo “4:20 de la madrugada, la hora adecuada”. Nunca entendiste para qué era adecuada, pero sabes que es parte del Cartel de Santa, y Santa quiere siempre lo mejor para sus creyentes.\n\nCuando por fin pasa el camión, te subes y notas que todos abordo llevan lentes de sol facheros facheritos.Primero piensas “Diablos, no recibí el fax en el que avisaban que era noche de drip camionero”, pero el conductor, en vez de darte tu ticket se quita los lentes, revelando que no es nadie más ni nadie menos que la mismísima rata con tiner.De la nada saca un porro y dice “¿Quieres? ”.";

std::string m4 = "Agarras el porrito y te das el toque más intenso de tu vida. La rata con tiner te da unos lentes de sol y te dice “Bienvenido a la secta marihuanera”. Extrañamente, se te quitan todas las ganas de volver a casa. “Este es mi nuevo hogar”, es lo que piensas.\n\nPierdes la noción del tiempo.¿Cuánto tiempo has estado dentro de ese camión? ¿Un minuto? ¿Una hora? ¿Un año? No lo sabes, pero no te importa, nunca vas a salir de ahí.";

std::string n4 = "Por más tentado que te ves de darte un trip con la rata con tiner y con toda la pena del mundo, rechazas el toque. De forma extraordinaria, todo a tu alrededor se oscurece totalmente. “¿Qué está pasando?” Te preguntas. De repente, empiezas a escuchar aplausos y se prenden unas luces. Mirando a tu alrededor te das cuenta que estás rodeado de todos tus amigos, los cuales te empiezan a decir “¡Felicidades!”. Te sientes extasiado. Sonrojado, no sabes qué decir mas que “Gracias”.\n\nA mi padre, gracias.A mi madre, adiós.Y a todos los niños... ¡Felicidades!";

std::string h3 = "No sabes por qué, pero te da mucha risa el número 69 y decides tomar ese camión. Cuando por fin llega, vez que no es un camión normal. A diferencia de los demás, este parece más un camión escolar pintado de azul. No sabes por qué, pero tiene un globo aerostático en el techo. Al subirte, te das cuenta que el conductor es el increíble Tyler “Ninja” Blevins, famoso streamer del gran éxito Fortnite: Battle Royale. Los pasajeros son todos niños chiquitos con playeras de la franquicia y cada uno de ellos está tratando de recrear uno de los bailes del juego.\n\nEn vez de seguir con la ruta, Ninja te pregunta “Where we dropping boys? !”.Le respondes que vas a tu casa.Inmediatamente sientes cómo el camión empieza a elevarse y en muy poco tiempo ya están flotando por los cielos.\n\nPasan unos cinco minutos y el camión empieza a descender.¡Sorpresa!El camión terminó siendo muy rápido, ¡Y además te está dejando justo enfrente de tu casa!Estás listo para bajarte… solo tienes una última decisión que tomar.";

std::string o4 = "Tuviste un excelente viaje, y crees que es adecuado agradecerle a Ninja por su servicio, pues, después de todo, no solo te trajo hasta tu casa, ¡Sino que lo hizo en tiempo récord! Das las gracias al camionero y bajas con la sonrisa más grande del mundo, pero antes de que puedas sacar las llaves de la casa escuchas a los niños del camión salir. Llegan corriendo contigo y te empiezas a golpear y hacer bailes de Fortnite alrededor tuyo.\n\nCasi a punto de desmayarte, escuchas a Ninja gritar “¡Hey, déjenlo en paz!”.Los golpes paran, y por un breve momento, te sientes aliviado, pero luego, Ninja se te acerca y te dice “Creo que no lo entiendes, niño, ¡Acabas de hacer una referencia a Fortnite!” después saca un pico de la cajuela del camión y te lo clava en el cráneo, matándote inmediatamente.";

std::string p4 = "Tuviste un excelente viaje, y crees que es adecuado agradecerle al camionero por su servicio, pero… no es cualquier conductor de autobus… es Tyler “Ninja” Blevins, tu celebrity crush más grande, tu Ultimate Bias, vaya. Esta será la primera y muy probablemente única ocasión en la que puedas decirle lo que realmente sientes. En vez de bajar por la puerta del autobús, vas directo al asiento de conductor y dices lo siguiente:\n\n“¿Ninja… te casarías conmigo?”\n\nNinja te responde con un “THE FUCK YOU SAY TO ME YOU LITTLE SHIT? AHAHAHAHAHAHA!How are you - how are you not in fucking school? You kiss your mother with that mouth? It’s called you - it’s called you kiss your mother with that fucking mouth? Huh? Huh? AHAHAH he so AHAH AH AHAHAHAHA - because the fucking youth of society - AYAHAHAHAHA AHAYAYO - YOU SHUT UP WHEN I’M TALKING TO YOU - YOU SHUT YOUR MOUTH!… Sí, acepto”.“Classic Ninja” Piensas mientras te limpias las lágrimas de alegría.\n\nY vivieron felices por siempre.";
